# Data Preprocessing Tools

## Importing the libraries

In [0]:
#importing three python libraries for preprocessing; refer to the libraries with their name for e.g. "np"
#numpy --> arrays & scientific computing
#matplotlib.pyplot --> graphs and plotting
#pandas --> machine learning and data analysis

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
#If using Google Colab, add the csv file before reading.
#X is the matrix of features.
#Y is the vector of the dependent variable (what we're predicting)

dataset = pd.read_csv('Data.csv') 
X = dataset.iloc[:, :-1].values #selecting all rows and all columns except the last one
Y = dataset.iloc[:, -1].values #selecting all rows in the last column

In [0]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [0]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [0]:
#sklearn is a machine learning library. 
#imputer is best for assigning data to missing values.

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') #replacement data is the mean value
imputer.fit(X[:, 1:3]) #imputer function calculates mean value of feature matrix
X[:, 1:3] = imputer.transform(X[:, 1:3]) #applying imputer transformation on feature matrix
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the independent variable

In [0]:
#Three unique values in countries are transformed into three separate columns.
#France is represented by 100, Spain by 001 and Germany by 010.
#normal digits aren't used (e.g. 1, 2,3) because the model might consider the countries as being ordered.
#remainder = "passthrough" enables the untransformed columns (age and salary) to be left unchanged.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [0]:
#Labelling the Yes/No values of the dependent variable as 0 and 1 bits.

from sklearn.preprocessing import  LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [0]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [0]:
#Training set is the segment of data set that will be used to train the ML model.
#Test set is the segment used to check whether the model works correctly. If the model accurately
#predicts the dependent variable values in the test set, then it is working correctly.
#test_size is split size. 0.2 means 20% of observations in both X and Y will go into the test set.
##random_state = 1 means that we get the same random factors from both X and Y.

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)  


In [0]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [0]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [0]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [0]:
print(y_test)

[0 1]


## Feature Scaling

In [0]:
#In some datasets, some features get more values than others (dominates them). 
#Dominated features may not be considered by the model.
#Feature scaling is used to prevent this concept. There are two main techniques: Normalization and Standardization
#Use normalization if features are distributed normally ( a normal curve); or else use standardiazation

#Standardization usually transforms values into something between -3 and 3. Do not standardize dummy variables
#(for e.g. country bits) because if you do, dummy variables will lose meaning. And since they are already in the range,
#applying standardization is not necessary.

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
